apiVersion: v1
kind: Service
metadata:
  name: {{ include "commit-boost.fullname" . }}-sidecar
  labels:
    {{- include "commit-boost.labels" . | nindent 4 }}
    app.kubernetes.io/component: sidecar
spec:
  type: {{ .Values.sidecar.service.type }}
  ports:
    - port: {{ .Values.sidecar.service.rpcPort }}
      targetPort: rpc
      protocol: TCP
      name: rpc
    - port: {{ .Values.sidecar.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "commit-boost.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: sidecar